

export enum AUTH_ACTION_TYPES {
    SET_CLIENT_TOKEN = 'SET_CLIENT_TOKEN',
    SET_AUTH_SESSION = 'SET_AUTH_SESSION',
    SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN',
    SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN',
    SET_EXPIRES_AT = 'SET_EXPIRES_AT'
}
